source/main/urls.py
from django.contrib import admin
from django.urls import path

from webapp.views.answer_views import AnswerCreateView, AnswerUpdateView, AnswerDeleteView
from webapp.views.collecting_views import CollectingTemplateView
from webapp.views.quiz_views import QuizCreateView, QuizDetailView, QuizUpdateView, QuizDeleteView, QuizIndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', QuizIndexView.as_view(), name='index'),
    path('quiz_create/', QuizCreateView.as_view(), name='quiz_create'),
    path('quiz_view/<int:pk>/', QuizDetailView.as_view(), name='quiz_view'),
    path('quiz_update/<int:pk>',QuizUpdateView.as_view(), name='quiz_update'),
    path('quiz_delete/<int:pk>',QuizDeleteView.as_view(), name='quiz_delete'),
    path('answer_create/<int:pk>',AnswerCreateView.as_view(), name='answer_create'),
    path('answer_update/<int:pk>',AnswerUpdateView.as_view(), name='answer_update'),
    path('answer_delete/<int:pk>',AnswerDeleteView.as_view(), name='answer_delete'),
    path('collecting/<int:pk>',CollectingTemplateView.as_view(), name='collecting')
]

source/webapp/models.py
from django.db import models


class Quiz(models.Model):
    question = models.TextField(max_length= 3000, null=False, blank=False, verbose_name='Вопрос')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')


class Answer(models.Model):
    answer = models.TextField(max_length=3000, null=False, blank=False, verbose_name='Ответ')
    poll = models.ForeignKey('webapp.Quiz', related_name='answer', verbose_name='Вопрос',
                             on_delete=models.CASCADE)


class Collecting(models.Model):
    quiz = models.ForeignKey('webapp.Quiz', related_name='collecting_quiz', verbose_name='Вопрос',
                             on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    answer = models.ForeignKey('webapp.Answer', related_name='collecting_answer', verbose_name='Вопрос',
                             on_delete=models.CASCADE)

source/webapp/forms.py
from django import forms
from webapp.models import  Answer, Quiz


class QuizForm(forms.ModelForm):

    class Meta:
        model = Quiz
        fields = ['question']


class AnswerForm(forms.ModelForm):

    class Meta:
        model = Answer
        fields = ['answer']

source/webapp/views/answer_views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, CreateView, View, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy

from webapp.forms import AnswerForm
from webapp.models import Answer, Quiz


class AnswerCreateView(CreateView):
    model = Answer
    template_name = 'answer/answer_create.html'
    form_class = AnswerForm

    def form_valid(self, form):
        quiz = get_object_or_404(Quiz, pk=self.kwargs.get('pk'))
        answer = form.save(commit=False)
        answer.poll = quiz
        answer.save()
        return redirect('quiz_view', pk=quiz.pk)


class AnswerUpdateView(UpdateView):
    model = Answer
    template_name = 'answer/answer_update.html'
    form_class = AnswerForm

    def get_success_url(self):
        return reverse('quiz_view',kwargs={'pk':self.object.poll.pk})

    # object = self.get_object()
    # # answer = get_object_or_404(Answer, pk=self.kwargs.get('pk'))
    # print(object.poll.pk)
    # return redirect('quiz_view', pk=object.poll.pk)
    # def form_valid(self, form):
    #     quiz = get_object_or_404(Quiz, pk=self.kwargs.get('pk'))
    #     print(quiz)
    #     return redirect('quiz_view', pk=quiz.pk)


# class AnswerDeleteView(DeleteView):
#     template_name = ''
#     model = Answer
#
#     def get(self, request, *args, **kwargs):
#         return self.delete(request, *args, **kwargs)
#
#     def get_success_url(self):
#         return reverse('index')

class AnswerDeleteView(DeleteView):
    template_name = 'answer/answer_delete.html'
    model = Answer
    success_url = reverse_lazy('index')

    def get_success_url(self):
        return reverse('quiz_view',kwargs={'pk':self.object.poll.pk})

source/webapp/views/collecting_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, TemplateView, DetailView
from django.urls import reverse, reverse_lazy

from webapp.models import Collecting, Quiz, Answer


# class CollectingTemplateView(View):
#
#    def get(self, request, *args, **kwargs):
#        collecting = Collecting.objects.all()
#        context = {
#            'collecions': collecions
#        }
#        return render(request, 'collecting/collecting_index.html', context)
#
class CollectingTemplateView(TemplateView):
    template_name = 'collecting/collecting_view.html'
    form_class = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        quiz = get_object_or_404(Quiz,pk=pk)
        answers = Answer.objects.all()
        answers= answers.filter(poll=quiz)
        context['quiz'] = quiz
        context['answers'] = answers
        return context

    def post(self, request, *args, **kwargs):
        quiz = request.POST['select']
        answers = Answer.objects.all()
        answers = answers.filter(pk=int(quiz))
        collecting = Collecting.objects.create(quiz=answers[0].poll, answer=answers[0])
        return redirect('index')


# class CollectingView(DetailView):
#     template_name = 'collecting/collecting_detal_view.html'
#
#     def get_queryset(self):
#         return Quiz.objects.all()
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['collect'] = QuizForm
#         return context

source/webapp/views/quiz_views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy

from webapp.forms import QuizForm
from webapp.models import Quiz, Answer


class QuizIndexView(ListView):
    template_name = 'quiz/index.html'
    context_object_name = 'quizs'
    paginate_by = 5
    paginate_orphans = 0

    def get_queryset(self):
        data = Quiz.objects.all()
        data= data.order_by('-created_at')

        # http://localhost:8000/?search=ygjkjhg
        # form = SimpleSearchForm(data=self.request.GET)
        # if form.is_valid():
        #     search = form.cleaned_data['search']
        #     if search:
        #         data = data.filter(Q(title__icontains=search) | Q(author__icontains=search))

        return data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['form'] = BasketForm
        return context

class QuizCreateView(CreateView):
    template_name = 'quiz/quiz_create.html'
    model = Quiz
    form_class = QuizForm

    def get_success_url(self):
        return reverse('index')


class QuizDetailView(DetailView):
    template_name = 'quiz/quiz_view.html'

    def get_queryset(self):
        return Quiz.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = QuizForm
        return context


class QuizUpdateView(UpdateView):
    template_name = 'quiz/quiz_update.html'
    form_class = QuizForm
    model = Quiz

    def get_success_url(self):
        return reverse('quiz_view', kwargs={'pk': self.object.pk})


class QuizDeleteView(DeleteView):
    template_name = 'quiz/quiz_delete.html'
    model = Quiz
    success_url = reverse_lazy('index')

source/webapp/templates/answer/answer_create.html
{% extends 'base.html' %}

{% block title %}Ответ{% endblock %}
{% block content %}
    <div class="col-6">
        <form action="{{ action_url }}" method="POST">
            {% csrf_token %}

            {% for field in form %}
                {% include 'partial/quiz_form.html' with form=field %}
            {% endfor %}
                  <input class="btn btn-primary" type="submit" value="Добавить">
        <a href="{% url 'index' %}" class="btn btn-primary">Отмена</a>
        </form>
    </div>
{% endblock %}

source/webapp/templates/answer/answer_delete.html
{% extends "base.html" %}
{% block title %}Delete{% endblock %}
{% block content %}
    <div class="col-9">
    <p class="text-center mt-5">Вы уверены что хотите удалить ответ под номером "{{ answer.pk }}"?</p>
    <form method="POST" action="{% url "answer_delete" answer.pk %}" class="text-center">
        {% csrf_token %}
        <p><input class=" btn btn-outline-dark btn-sm mb-1 mr-2" type="submit" value="Confirm">
        <a class=" btn btn-outline-dark btn-sm mb-1 mr-2" href=" {% url 'index' %}" role="button">Cancel
        </a></p>
{#            <p><a href="{% url "find" article.pk %}">Cancel</a></p>#}
    </form>
    </div>
{% endblock %}

source/webapp/templates/answer/answer_update.html
{% extends 'base.html' %}

{% block title %}Редактирование ответа{% endblock %}

{% block content %}
    <h1>Редактирование ответа</h1>
       <form action="{%  url 'answer_update' answer.pk %}" method="POST">
            {% csrf_token %}

            {% for field in form %}
                {% include 'partial/quiz_form.html' with form=field %}
            {% endfor %}
            <input class="btn btn-primary" type="submit" value="Редактировать">
        <a href="{% url 'index' %}" class="btn btn-primary">Отмена</a>
        </form>
{% endblock %}

source/webapp/templates/answer/index.html
{% extends 'base.html' %}

{% block title %}Quiz{% endblock %}
{% block menu %}
<li class="nav-item active">
    <a class="nav-link" href="{% url 'quiz_create' %}">Добавить вопрос <span class="sr-only">(current)</span></a>
</li>

{% endblock %}
{% block content %}
{#    <form action="{% url 'index' %}" method="GET">#}
{#        <div class="form-group row mt-2">#}
{#            <label for="colFormLabelSm" class="col-sm-1 col-form-label col-form-label-sm">Поиск</label>#}
{#            <div class="col-sm-4">#}
{#                <input type="text" name="name" class="form-control form-control-sm" id="colFormLabelSm"#}
{#                       placeholder="Введите название">#}
{#            </div>#}
{#            <div class="form-group row">#}
{#                <div class="col-sm-2">#}
{#                    <button type="submit" class="btn btn-primary btn-sm">Поиск</button>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </form>#}
{#    {% if is_paginated %}#}
{#        {% include 'partial/pagination.html' %}#}
{#    {% endif %}#}
    <div class="row">
        {% for quiz in quizs %}
            {% include 'partial/quiz_list.html' %}
        {% endfor %}
    </div>
    <div class="row justify-content-md-center">
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
        {% endif %}
    </div>
{% endblock %}

source/webapp/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My SHOP{% endblock %}</title>
    <link rel="stylesheet" href="{% static "/css/style.css" %}">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Главная <span class="sr-only">(current)</span></a>
                </li>
                {% block menu %}
                {% endblock %}
            </ul>
        </div>
    </nav>
</header>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</html>

source/webapp/templates/collecting/collecting_detal_view.html
{% extends 'base.html' %}

{% block title %}View{% endblock %}

{% block menu %}
{% endblock %}

{% block content %}
     {{ collect }}
{#    <p>Категория: <a href="{% url 'filter_category' product.category%}">{{ product.get_category_display }}</a></p>#}
{#    <p>Описание: {{ product.description }}</p>#}
{#    <p>Остаток: {{ product.amount }}</p>#}
{#    <p>Цена: {{ product.price }}</p>#}
{% endblock %}

source/webapp/templates/collecting/collecting_view.html
{% extends 'base.html' %}

{% block title %}View{% endblock %}

{% block menu %}
{% endblock %}

{% block content %}
      <h1 class="p-3">{{ quiz.question}}</h1>
     {% if answers %}
         <form action="{%  url 'collecting' quiz.pk %}" method="POST">
         {% csrf_token %}
          {% for answer in quiz.answer.all %}

            <div class="form-check">
          <input class="form-check-input" type="radio" name="select" id="gridRadios2" value="{{ answer.pk }}">
          <label class="form-check-label" for="gridRadios2">
              {{ answer.answer}}
          </label>
        </div>
          {% endfor %}
         <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">Ответить</button>
    </div>
  </div>
         </form>
      {% endif %}
{#    <p>Категория: <a href="{% url 'filter_category' product.category%}">{{ product.get_category_display }}</a></p>#}
{#    <p>Описание: {{ product.description }}</p>#}
{#    <p>Остаток: {{ product.amount }}</p>#}
{#    <p>Цена: {{ product.price }}</p>#}
{% endblock %}

source/webapp/templates/partial/collecting_list.html
<div class="card m-2" style="width: 18rem;">
  <div class="card-body">
{#    <p class="card-text">{{ quiz.question }}</p>#}
      <a href="{% url 'quiz_view' collect.collecting_quiz.pk %}"><h1>{{ collect.collecting_quiz.question }}</h1></a>
        {{ collect }}
      {#      {% if quiz.answer.all %}#}
{#          {% for answer in quiz.answer.all %}#}
{#              <p>{{ answer.answer }}</p>#}
{#              <a href="{% url 'answer_update' answer.pk %}" class="btn btn-primary">Ре</a>#}
{#              <a href="{% url 'answer_delete' answer.pk %}" class="btn btn-primary">Уд</a>#}
{#          {% endfor %}#}
{#      {% endif %}#}
{#        <br>#}
{#      <a href="{% url 'quiz_update' quiz.pk %}" class="btn btn-primary">Редактировать</a>#}
{#      <a href="{% url 'quiz_delete' quiz.pk %}" class="btn btn-primary">Удалить</a>#}
{#      {% url 'quiz_delete' quiz.pk as action_url %}#}
{#      {% include 'partial/quiz_form.html' with action_url=action_url%}#}
{#      <a href="{% url 'answer_create' quiz.pk %}" class="btn btn-primary">Добавить ответ</a>#}
  </div>
</div>

source/webapp/templates/partial/pagination.html
<div class="pagination">
    <span class="step-links">
        <a class="btn btn-outline-dark btn-sm mb-1 mr-2" href="?{% if search %}search={{ search }}&{% endif %}page=1">&laquo; В начало</a>
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-dark btn-sm mb-1 mr-2" href="?{% if search %}search={{ search }}&{% endif %}page={{ page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="btn btn-outline-dark btn-sm mb-1 mr-2 page-disabled">Назад</span>
        {% endif %}
        <form class="current-page" method="get">
            <label for="page">
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
                {% if search %}<input type="hidden" name="search" value="{{ search }}">{% endif %}
            </label>
        </form>

        {% if page_obj.has_next %}
            <a class="btn btn-outline-dark btn-sm mb-1 mr-2" href="?{% if search %}search={{ search }}&{% endif %}page={{ page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class=" btn btn-outline-dark btn-sm mb-1 mr-2 page-disabled">Далее</span>
        {% endif %}
        <a class="btn btn-outline-dark btn-sm mb-1 mr-2" href="?{% if search %}search={{ search }}&{% endif %}page={{ page_obj.paginator.num_pages }}">В конец &raquo;</a>
    </span>
</div>
{##}
{#<div class="pagination">#}
{#    <span class="step-links">#}
{#        <a href="?page=1">&laquo; В начало</a>#}
{#        {% if page_obj.has_previous %}#}
{#            <a href="?page={{ page_obj.previous_page_number }}">Назад</a>#}
{#        {% else %}#}
{#            <span class="page-disabled">Назад</span>#}
{#        {% endif %}#}
{#        <form class="current-page" method="get">#}
{#            <label for="page">#}
{#                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">#}
{#                из {{ page_obj.paginator.num_pages }}.#}
{#            </label>#}
{#        </form>#}
{#        {% if page_obj.has_next %}#}
{#            <a href="?page={{ page_obj.next_page_number }}">Далее</a>#}
{#        {% else %}#}
{#            <span class="page-disabled">Далее</span>#}
{#        {% endif %}#}
{#        <a href="?page={{ page_obj.paginator.num_pages }}">В конец &raquo;</a>#}
{#    </span>#}
{#</div>#}

source/webapp/templates/partial/quiz_form.html
<div class="form-group">
    <div class="form-group">
        <label for="name">{{ form.label }}</label>
        <p>{{ form }}</p>
        {% for error in form.errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    </div>
</div>

source/webapp/templates/partial/quiz_list.html
<div class="card m-2" style="width: 18rem;">
  <div class="card-body">
{#    <p class="card-text">{{ quiz.question }}</p>#}
      <a href="{% url 'quiz_view' quiz.pk %}"><h1>{{ quiz.question }}</h1></a>
{#      {% if quiz.answer.all %}#}
{#          {% for answer in quiz.answer.all %}#}
{#              <p>{{ answer.answer }}</p>#}
{#              <a href="{% url 'answer_update' answer.pk %}" class="btn btn-primary">Ре</a>#}
{#              <a href="{% url 'answer_delete' answer.pk %}" class="btn btn-primary">Уд</a>#}
{#          {% endfor %}#}
{#      {% endif %}#}
{#        <br>#}
      <a href="{% url 'quiz_update' quiz.pk %}" class="btn btn-primary btn-lg btn-block">Редактировать</a>
        <a href="{% url 'collecting' quiz.pk %}" class="btn btn-primary btn-lg btn-block">Пройти</a>
      <a href="{% url 'quiz_delete' quiz.pk %}" class="btn btn-primary btn-lg btn-block">Удалить</a>
      <a href="{% url 'answer_create' quiz.pk %}" class="btn btn-primary btn-lg btn-block">Добавить ответ</a>
      {% url 'quiz_delete' quiz.pk as action_url %}
      {% include 'partial/quiz_form.html' with action_url=action_url%}
  </div>
</div>


{#<div class="col-1 col-sm-3 col-md-3 p-3">#}
{#    <div class="card bg-light mb-3" style="max-width: 18rem;">#}
{#        <div class="card-header"><a href="{% url 'view' product.pk %}">{{ product.name }}</a></div>#}
{#        <div class="card-body">#}
{#            <p class="card-title">Цена: {{ product.price }}</p>#}
{#            <p class="card-text">Категория: <a#}
{#                    href="{% url 'filter_category' product.category %}">{{ product.get_category_display }}.</a></p>#}
{#            <a class="btn btn-primary" href="{% url 'product_update' product.pk %}" role="button">#}
{#                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor"#}
{#                     xmlns="http://www.w3.org/2000/svg">#}
{#                    <path fill-rule="evenodd"#}
{#                          d="M11.293 1.293a1 1 0 0 1 1.414 0l2 2a1 1 0 0 1 0 1.414l-9 9a1 1 0 0 1-.39.242l-3 1a1 1 0 0 1-1.266-1.265l1-3a1 1 0 0 1 .242-.391l9-9zM12 2l2 2-9 9-3 1 1-3 9-9z"/>#}
{#                    <path fill-rule="evenodd"#}
{#                          d="M12.146 6.354l-2.5-2.5.708-.708 2.5 2.5-.707.708zM3 10v.5a.5.5 0 0 0 .5.5H4v.5a.5.5 0 0 0 .5.5H5v.5a.5.5 0 0 0 .5.5H6v-1.5a.5.5 0 0 0-.5-.5H5v-.5a.5.5 0 0 0-.5-.5H3z"/>#}
{#                </svg>#}
{#                Редак.#}
{#            </a>#}
{#            <a class="btn btn-primary" href="{% url 'product_delete' product.pk %}" role="button">#}
{#                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor"#}
{#                     xmlns="http://www.w3.org/2000/svg">#}
{#                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>#}
{#                    <path fill-rule="evenodd"#}
{#                          d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>#}
{#                </svg>#}
{#                Удалить#}
{#            </a>#}
{#            {% url "basket_create" product.pk as action_url %}#}
{#            {% include 'partial/basket_form.html' with action_url=action_url%}#}
{#        </div>#}
{#    </div>#}
{#</div>#}

source/webapp/templates/quiz/index.html
{% extends 'base.html' %}

{% block title %}Hello{% endblock %}
{% block menu %}
<li class="nav-item active">
    <a class="nav-link" href="{% url 'quiz_create' %}">Добавить вопрос <span class="sr-only">(current)</span></a>
</li>

{% endblock %}
{% block content %}
{#    <form action="{% url 'index' %}" method="GET">#}
{#        <div class="form-group row mt-2">#}
{#            <label for="colFormLabelSm" class="col-sm-1 col-form-label col-form-label-sm">Поиск</label>#}
{#            <div class="col-sm-4">#}
{#                <input type="text" name="name" class="form-control form-control-sm" id="colFormLabelSm"#}
{#                       placeholder="Введите название">#}
{#            </div>#}
{#            <div class="form-group row">#}
{#                <div class="col-sm-2">#}
{#                    <button type="submit" class="btn btn-primary btn-sm">Поиск</button>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </form>#}
{#    {% if is_paginated %}#}
{#        {% include 'partial/pagination.html' %}#}
{#    {% endif %}#}
    <div class="row">
        {% for quiz in quizs %}
            {% include 'partial/quiz_list.html' %}
        {% endfor %}
    </div>
    <div class="row justify-content-md-center">
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
        {% endif %}
    </div>
{% endblock %}

source/webapp/templates/quiz/quiz_create.html
{% extends 'base.html' %}

{% block title %}Add new Task{% endblock %}
{% block content %}
    <div class="col-6">
        <form action="{% url 'quiz_create' %}" method="POST">
            {% csrf_token %}

            {% for field in form %}
                {% include 'partial/quiz_form.html' with form=field %}
            {% endfor %}
            <input class="btn btn-primary" type="submit" value="Добавить Вопрос">
        <a href="{% url 'index' %}" class="btn btn-primary">Отмена</a>
        </form>
    </div>
{% endblock %}

source/webapp/templates/quiz/quiz_delete.html
{% extends "base.html" %}
{% block title %}Delete{% endblock %}
{% block content %}
    <div class="col-9">
    <p class="text-center mt-5">Вы уверены что хотите удалить вопрос под номером "{{ quiz.pk }}"?</p>
    <form method="POST" action="{% url "quiz_delete" quiz.pk %}" class="text-center">
        {% csrf_token %}
        <p><input class=" btn btn-outline-dark btn-sm mb-1 mr-2" type="submit" value="Confirm">
        <a class=" btn btn-outline-dark btn-sm mb-1 mr-2" href=" {% url 'quiz_view' quiz.pk %}" role="button">Cancel
        </a></p>
{#            <p><a href="{% url "find" article.pk %}">Cancel</a></p>#}
    </form>
    </div>
{% endblock %}

source/webapp/templates/quiz/quiz_update.html
{% extends 'base.html' %}

{% block title %}Редактирование Вопроса{% endblock %}
{% block content %}
    <div class="col-6">
        <form action="{% url 'quiz_update' quiz.pk %}" method="POST">
            {% csrf_token %}
            {% for field in form %}
                {% include 'partial/quiz_form.html' with form=field %}
            {% endfor %}
            <input class="btn btn-primary" type="submit" value="Сохранить изменение">
        <a href="{% url 'index' %}" class="btn btn-primary">Отмена</a>
        </form>
    </div>
{% endblock %}